# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RundezvousS4' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RundezvousS4
  pod ‘Firebase’
  pod ‘Firebase/Core’
  pod ‘Firebase/Storage’
  pod ‘Firebase/Auth’
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.5'

  target 'RundezvousS4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
